export const workflowNodesDimensions = {
    padding: 20,
    scriptWidth: 400,
    scriptHeight: 60,
    connectionPointWidth: 180,
    connectionPointHeight: 50,
    groupLabel: "\u200E"
};

export const workflowTrailingCode = "\n\n#Generated by CanvasBlocks plugin\n_return_output_data()";

export const supportedLanguagesNamePrefixes = ["py", "js", "lua"];

export const scriptCodeBlockLanguageSuffix = "canvasblock";
export const canvasBlockSettingsLanguageName = scriptCodeBlockLanguageSuffix + "settings"; // "canvasblocksettings"
export const canvasBlockConnectionPointLanguageName = scriptCodeBlockLanguageSuffix + "connectionpoint"; // "canvasblockconnectionpoint"

export const languageToLanguageNameMap: Record<string, string> = {
    python: "py",
    javascript: "js",
    lua: "lua"
};